name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update Homebrew Formula
        run: |
          # Extract version from tag (remove 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/v}
          
          # Ensure we're on the main branch
          git checkout main
          
          # Download checksums
          curl -L -o checksums.txt "https://github.com/wingsuitist/retry/releases/download/v${VERSION}/checksums.txt"
          
          # Extract checksums for each platform
          DARWIN_X86_64_SHA=$(grep "retry_${VERSION}_Darwin_x86_64.tar.gz" checksums.txt | cut -d' ' -f1)
          DARWIN_ARM64_SHA=$(grep "retry_${VERSION}_Darwin_arm64.tar.gz" checksums.txt | cut -d' ' -f1)
          LINUX_X86_64_SHA=$(grep "retry_${VERSION}_Linux_x86_64.tar.gz" checksums.txt | cut -d' ' -f1)
          LINUX_I386_SHA=$(grep "retry_${VERSION}_Linux_i386.tar.gz" checksums.txt | cut -d' ' -f1)
          LINUX_ARM64_SHA=$(grep "retry_${VERSION}_Linux_arm64.tar.gz" checksums.txt | cut -d' ' -f1)
          
          # Update version in formula
          sed -i "s/version \".*\"/version \"${VERSION}\"/" Formula/retry.rb
          
          # Update URLs and checksums
          sed -i "s|retry_[0-9.]*_Darwin_x86_64.tar.gz|retry_${VERSION}_Darwin_x86_64.tar.gz|g" Formula/retry.rb
          sed -i "s|retry_[0-9.]*_Darwin_arm64.tar.gz|retry_${VERSION}_Darwin_arm64.tar.gz|g" Formula/retry.rb
          sed -i "s|retry_[0-9.]*_Linux_x86_64.tar.gz|retry_${VERSION}_Linux_x86_64.tar.gz|g" Formula/retry.rb
          sed -i "s|retry_[0-9.]*_Linux_i386.tar.gz|retry_${VERSION}_Linux_i386.tar.gz|g" Formula/retry.rb
          sed -i "s|retry_[0-9.]*_Linux_arm64.tar.gz|retry_${VERSION}_Linux_arm64.tar.gz|g" Formula/retry.rb
          
          # Update version in URLs
          sed -i "s|/v[0-9.]*/|/v${VERSION}/|g" Formula/retry.rb
          
          # Update checksums
          sed -i "/Darwin_x86_64.tar.gz/,+1s/sha256 \".*\"/sha256 \"${DARWIN_X86_64_SHA}\"/" Formula/retry.rb
          sed -i "/Darwin_arm64.tar.gz/,+1s/sha256 \".*\"/sha256 \"${DARWIN_ARM64_SHA}\"/" Formula/retry.rb
          sed -i "/Linux_x86_64.tar.gz/,+1s/sha256 \".*\"/sha256 \"${LINUX_X86_64_SHA}\"/" Formula/retry.rb
          sed -i "/Linux_i386.tar.gz/,+1s/sha256 \".*\"/sha256 \"${LINUX_I386_SHA}\"/" Formula/retry.rb
          sed -i "/Linux_arm64.tar.gz/,+1s/sha256 \".*\"/sha256 \"${LINUX_ARM64_SHA}\"/" Formula/retry.rb
          
          # Commit and push the updated formula
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Formula/retry.rb
          git commit -m "chore: update Homebrew formula to v${VERSION} with pre-compiled binaries" || exit 0
          git push origin main
