name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/retry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
