name: update-formula

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  bump-formula:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set version variables
        id: vars
        run: |
          echo "tag=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          echo "tarball=${{ github.event.release.tarball_url }}" >> "$GITHUB_OUTPUT"

      - name: Calculate checksum
        run: |
          curl -Ls "${{ steps.vars.outputs.tarball }}" | sha256sum | awk '{print $1}' > sha.txt
          echo "sha=$(cat sha.txt)" >> "$GITHUB_ENV"

      - name: Update formula
        run: |
          sed -i "s#url \".*\"#url \"https://github.com/wingsuitist/retry/archive/refs/tags/${{ steps.vars.outputs.tag }}.tar.gz\"#" Formula/retry.rb
          sed -i "s/sha256 \".*\"/sha256 \"${sha}\"/" Formula/retry.rb

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/retry.rb
          git commit -m "chore: update Homebrew formula for ${{ steps.vars.outputs.tag }}"
          git push

